require("@nomicfoundation/hardhat-toolbox");
require("hardhat-gas-reporter");
require("@nomicfoundation/hardhat-foundry");
require('dotenv').config();


/** @type import('hardhat/config').HardhatUserConfig */
module.exports = {
  solidity: "0.8.28",
  gasReporter: {
    enabled: true,
    excludeAutoGeneratedGetters: true,
    reportPureAndViewMethods: true,
    L1Etherscan: process.env.ETHERSCAN_API_KEY, // This is needed in conjunction with the CMC key if you want to fetch the gas price for Ethereum L1
    currency: "USD", // Can be any currency supported by the CoinMarketCap API (e.g., EUR, PKR, etc.)
    coinmarketcap: process.env.COINMARKETCAP_API_KEY, 
    includeIntrinsicGas: true, // Each function call includes the intrinsic gas cost of 21000 when an EOA calls it
    showUncalledMethods: true
  }
};
